version: '3'
services:
  client-test:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - ./client:/app
      - ./shared:/shared
    depends_on:
      - server-test
  server-test:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 9229:9229
    volumes:
      - ./server:/server
      - ./shared:/shared
  # depends_on:
  #   - database

  # database:
  #   image: postgres:latest
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=test_docker_username
  #     - POSTGRES_PASSWORD=test_docker_password
  #     - POSTGRES_DB=test_docker_db
  #   volumes:
  #     - ./database:/var/lib/postgresql/data
